name: 'Hydra CI Health Check'
description: 'Checks all builds for a Hydra evaluation'
author: 'RAD-Development'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'

# Define your inputs here.
inputs:
  evaluation-name:
    description:
      'Evaluation to be checked. Tip: can be a PR (github.event.number) or
      branch (github.ref_name)'
    required: true
  hydra-url:
    description: 'Base URL for Hydra API'
    required: true

runs:
  using: node20
  main: dist/index.js
